
[semester]
january.name = "3 weeks January"
january.weeks = 3

spring.name = "13 weeks Spring"
spring.weeks = 13

june.name = "3 weeks June"
june.weeks = 3

autumn.name = "13 weeks Autumn"
autumn.weeks = 13

[semester.2023]
january.week-start = 1
spring.week-start = 5
june.week-start = 23
autumn.week-start = 35
autumn.week-breaks = 42

[semester.2024]
january.week-start = 1
january.week = [
    "Closed",
    "Closed",
    "Closed"
]

spring.week-start = 5
june.week-start = 24
#autumn.week-start = 34
#autumn.week-breaks = 42


[dtu]
# The course database primary link
course-base = "https://kurser.dtu.dk"


[course.01001]
home = "https://01001.compute.dtu.dk"
[course.01002]
home = "https://01002.compute.dtu.dk"
[course.01003]
home = "https://01003.compute.dtu.dk"
[course.01004]
home = "https://01004.compute.dtu.dk"

[course.02002]
home = "https://02002.compute.dtu.dk/da/index.html"
[course.02003]
home = "https://02002.compute.dtu.dk/index.html"
